### ISSUE TITLE
rollup plugin stops working when dependencies provided

### ISSUE THREAD

**Issue by eshikerya** [theBenForce/serverless-rollup-plugin#88]
src/utils/installDependencies.ts:28

require of json file returns JSON object, not the string, afaik;)
always failing with `SyntaxError: Unexpected token o in JSON at position 1`

**Comment by perrin4869** [comment]
Oh right thanks! Maybe a result of not being able to decide between `require` and `fs.readFileSync` 😅
I'll fix it tomorrow, my PC is out of commission for a few more hours. PR welcome! Bonus points if you can add a regression test

**Comment by perrin4869** [comment]
Thanks!

**Comment by eshikerya** [comment]
had no time to cover with test, sorry:)
